%% draw stimuli for BH
Bidx = B;
BTidx = BT;
Tidx = T;
TTidx = BLOCK(BB).Trial(T).TT;

% target
xy = BLOCK(Bidx).Trial(Tidx).Pos(...
    BLOCK(Bidx).Trial(Tidx).TarPos,:);

Screen('DrawTexture',HARDWARE.window,...
    STIM.TrialType(TTidx).targtex, [],...
    CenterRectOnPoint(STIM.TrialType(TTidx).TRect,...
    xy(1),xy(2)));

% distractors
for di = 1:STIM.TrialType(TTidx).nDistract
    xy = BLOCK(Bidx).Trial(Tidx).Pos(...
        BLOCK(Bidx).Trial(Tidx).DistPos(di),:);

    Screen('DrawTexture',HARDWARE.window,...
        STIM.TrialType(TTidx).disttex(di), [],...
        CenterRectOnPoint(STIM.TrialType(TTidx).DRect,...
        xy(1),xy(2)));
end