% draw stimuli for BHdrawstim_BH
dummyrect = CenterRectOnPoint(FixRect*5,...
    HARDWARE.PixWidth/2,HARDWARE.PixHeight/2);
Screen('FillOval', HARDWARE.window,...
    STIM.Fix.Color.*HARDWARE.white,dummyrect+300);