STORY.FontSize = 16;

STORY.anger(1).text = [...
    'Blababla line 1\n' ...
    'Some more text to make people angry\n' ...
    'And yet another line of text\n' ...
    'etcetera etcetera...\n\n'...
    '>> Press any key to start <<'];

STORY.anger(2).text = [...
    'Blababla line 1\n' ...
    'Some more text to make people angry\n' ...
    'And yet another line of text\n' ...
    'etcetera etcetera...\n\n'...
    '>> Press any key to start <<'];

STORY.happy(1).text = [...
    'Blababla line 1\n' ...
    'Some more text to make people happy\n' ...
    'And yet another line of text\n' ...
    'etcetera etcetera...\n\n'...
    '>> Press any key to start <<'];

STORY.happy(2).text = [...
    'Blababla line 1\n' ...
    'Some more text to make people happy\n' ...
    'And yet another line of text\n' ...
    'etcetera etcetera...\n\n'...
    '>> Press any key to start <<'];