STORY.FontSize = 16;

STORY.anger(1).text = [...
    'Blababla line 1\n\n' ...
    'Some more text to make people angry\n\n' ...
    'And yet another line of text\n\n' ...
    'etcetera etcetera...\n\n\n'...
    '>> Press any key to start <<'];

STORY.anger(2).text = [...
    'Blababla line 1\n\n' ...
    'Some more text to make people angry\n\n' ...
    'And yet another line of text\n\n' ...
    'etcetera etcetera...\n\n\n'...
    '>> Press any key to start <<'];

STORY.happy(1).text = [...
    'Blababla line 1\n\n' ...
    'Some more text to make people happy\n\n' ...
    'And yet another line of text\n\n' ...
    'etcetera etcetera...\n\n\n'...
    '>> Press any key to start <<'];

STORY.happy(2).text = [...
    'Blababla line 1\n\n' ...
    'Some more text to make people happy\n\n' ...
    'And yet another line of text\n\n' ...
    'etcetera etcetera...\n\n\n'...
    '>> Press any key to start <<'];